package nav_msgs;

public interface GetMapFeedback {
  static final java.lang.String _TYPE = "nav_msgs/GetMapFeedback";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#feedback definition\n"
      + "";
}
