package nav_msgs;

public interface GetMapActionFeedback {
  static final java.lang.String _TYPE = "nav_msgs/GetMapActionFeedback";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "Header header\n"
      + "actionlib_msgs/GoalStatus status\n"
      + "nav_msgs/GetMapFeedback feedback\n"
      + "";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  nav_msgs.GetMapFeedback getFeedback();
  void setFeedback(nav_msgs.GetMapFeedback value);
}
