package nav_msgs;

public interface GetMapResult {
  static final java.lang.String _TYPE = "nav_msgs/GetMapResult";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#result definitionnav_msgs/OccupancyGrid map\n"
      + "";
}
