package object_recognition_msgs;

public interface ObjectRecognitionActionGoal {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionActionGoal";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "Header header\n"
      + "actionlib_msgs/GoalID goal_id\n"
      + "object_recognition_msgs/ObjectRecognitionGoal goal\n"
      + "";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  object_recognition_msgs.ObjectRecognitionGoal getGoal();
  void setGoal(object_recognition_msgs.ObjectRecognitionGoal value);
}
