package object_recognition_msgs;

public interface ObjectRecognitionGoal {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionGoal";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#goal definition# Optional ROI to use for the object detection\n"
      + "bool use_roi\n"
      + "float32[] filter_limits\n"
      + "";
  boolean getUseRoi();
  void setUseRoi(boolean value);
  float[] getFilterLimits();
  void setFilterLimits(float[] value);
}
