package object_recognition_msgs;

public interface ObjectRecognitionActionResult {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionActionResult";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "Header header\n"
      + "actionlib_msgs/GoalStatus status\n"
      + "object_recognition_msgs/ObjectRecognitionResult result\n"
      + "";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  object_recognition_msgs.ObjectRecognitionResult getResult();
  void setResult(object_recognition_msgs.ObjectRecognitionResult value);
}
