package object_recognition_msgs;

public interface ObjectRecognitionAction {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionAction";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "ObjectRecognitionActionGoal action_goal\n"
      + "ObjectRecognitionActionResult action_result\n"
      + "ObjectRecognitionActionFeedback action_feedback\n"
      + "";
  object_recognition_msgs.ObjectRecognitionActionGoal getActionGoal();
  void setActionGoal(object_recognition_msgs.ObjectRecognitionActionGoal value);
  object_recognition_msgs.ObjectRecognitionActionResult getActionResult();
  void setActionResult(object_recognition_msgs.ObjectRecognitionActionResult value);
  object_recognition_msgs.ObjectRecognitionActionFeedback getActionFeedback();
  void setActionFeedback(object_recognition_msgs.ObjectRecognitionActionFeedback value);
}
