package object_recognition_msgs;

public interface ObjectRecognitionActionFeedback {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionActionFeedback";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "Header header\n"
      + "actionlib_msgs/GoalStatus status\n"
      + "object_recognition_msgs/ObjectRecognitionFeedback feedback\n"
      + "";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  object_recognition_msgs.ObjectRecognitionFeedback getFeedback();
  void setFeedback(object_recognition_msgs.ObjectRecognitionFeedback value);
}
