package object_recognition_msgs;

public interface ObjectRecognitionFeedback {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionFeedback";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#feedback definition\n"
      + "#no feedback\n"
      + "";
}
