package moveit_msgs;

public interface ExecuteTrajectoryGoal {
  static final java.lang.String _TYPE = "moveit_msgs/ExecuteTrajectoryGoal";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#goal definition# The trajectory to execute\n"
      + "RobotTrajectory trajectory\n"
      + "";
  moveit_msgs.RobotTrajectory getTrajectory();
  void setTrajectory(moveit_msgs.RobotTrajectory value);
}
