package moveit_msgs;

public interface ExecuteTrajectoryAction {
  static final java.lang.String _TYPE = "moveit_msgs/ExecuteTrajectoryAction";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "ExecuteTrajectoryActionGoal action_goal\n"
      + "ExecuteTrajectoryActionResult action_result\n"
      + "ExecuteTrajectoryActionFeedback action_feedback\n"
      + "";
  moveit_msgs.ExecuteTrajectoryActionGoal getActionGoal();
  void setActionGoal(moveit_msgs.ExecuteTrajectoryActionGoal value);
  moveit_msgs.ExecuteTrajectoryActionResult getActionResult();
  void setActionResult(moveit_msgs.ExecuteTrajectoryActionResult value);
  moveit_msgs.ExecuteTrajectoryActionFeedback getActionFeedback();
  void setActionFeedback(moveit_msgs.ExecuteTrajectoryActionFeedback value);
}
