package moveit_msgs;

public interface ExecuteTrajectoryResult {
  static final java.lang.String _TYPE = "moveit_msgs/ExecuteTrajectoryResult";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#result definition\n"
      + "# Error code - encodes the overall reason for failure\n"
      + "MoveItErrorCodes error_code\n"
      + "";
  moveit_msgs.MoveItErrorCodes getErrorCode();
  void setErrorCode(moveit_msgs.MoveItErrorCodes value);
}
