package moveit_msgs;

public interface MoveGroupSequenceAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/MoveGroupSequenceAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nMoveGroupSequenceActionGoal action_goal\nMoveGroupSequenceActionResult action_result\nMoveGroupSequenceActionFeedback action_feedback\n";
  moveit_msgs.MoveGroupSequenceActionGoal getActionGoal();
  void setActionGoal(moveit_msgs.MoveGroupSequenceActionGoal value);
  moveit_msgs.MoveGroupSequenceActionResult getActionResult();
  void setActionResult(moveit_msgs.MoveGroupSequenceActionResult value);
  moveit_msgs.MoveGroupSequenceActionFeedback getActionFeedback();
  void setActionFeedback(moveit_msgs.MoveGroupSequenceActionFeedback value);
}
