package moveit_msgs;

public interface MoveGroupGoal {
  static final java.lang.String _TYPE = "moveit_msgs/MoveGroupGoal";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#goal definition# Motion planning request to pass to planner\n"
      + "MotionPlanRequest request\n"
      + "# Planning options\n"
      + "PlanningOptions planning_options\n"
      + "";
  moveit_msgs.MotionPlanRequest getRequest();
  void setRequest(moveit_msgs.MotionPlanRequest value);
  moveit_msgs.PlanningOptions getPlanningOptions();
  void setPlanningOptions(moveit_msgs.PlanningOptions value);
}
