package moveit_msgs;

public interface MoveGroupSequenceActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/MoveGroupSequenceActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nmoveit_msgs/MoveGroupSequenceFeedback feedback";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  moveit_msgs.MoveGroupSequenceFeedback getFeedback();
  void setFeedback(moveit_msgs.MoveGroupSequenceFeedback value);
}
