package moveit_msgs;

public interface MoveGroupSequenceFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/MoveGroupSequenceFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#feedback definition\n\n# The internal state that the move group action currently is in\nstring state";
  java.lang.String getState();
  void setState(java.lang.String value);
}
