package moveit_msgs;

public interface MoveGroupSequenceGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/MoveGroupSequenceGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#goal definition# A list of motion commands - one for each section of the sequence\nMotionSequenceRequest request\n\n# Planning options\nPlanningOptions planning_options\n";
  moveit_msgs.MotionSequenceRequest getRequest();
  void setRequest(moveit_msgs.MotionSequenceRequest value);
  moveit_msgs.PlanningOptions getPlanningOptions();
  void setPlanningOptions(moveit_msgs.PlanningOptions value);
}
