package moveit_msgs;

public interface PickupAction {
  static final java.lang.String _TYPE = "moveit_msgs/PickupAction";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "PickupActionGoal action_goal\n"
      + "PickupActionResult action_result\n"
      + "PickupActionFeedback action_feedback\n"
      + "";
  moveit_msgs.PickupActionGoal getActionGoal();
  void setActionGoal(moveit_msgs.PickupActionGoal value);
  moveit_msgs.PickupActionResult getActionResult();
  void setActionResult(moveit_msgs.PickupActionResult value);
  moveit_msgs.PickupActionFeedback getActionFeedback();
  void setActionFeedback(moveit_msgs.PickupActionFeedback value);
}
