package moveit_msgs;

public interface PickupGoal {
  static final java.lang.String _TYPE = "moveit_msgs/PickupGoal";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#goal definition# An action for picking up an object\n"
      + "# The name of the object to pick up (as known in the planning scene)\n"
      + "string target_name\n"
      + "# which group should be used to plan for pickup\n"
      + "string group_name\n"
      + "# which end-effector to be used for pickup (ideally descending from the group above)\n"
      + "string end_effector\n"
      + "# a list of possible grasps to be used. At least one grasp must be filled in\n"
      + "Grasp[] possible_grasps\n"
      + "# the name that the support surface (e.g. table) has in the collision map\n"
      + "# can be left empty if no name is available\n"
      + "string support_surface_name\n"
      + "# whether collisions between the gripper and the support surface should be acceptable\n"
      + "# during move from pre-grasp to grasp and during lift. Collisions when moving to the\n"
      + "# pre-grasp location are still not allowed even if this is set to true.\n"
      + "bool allow_gripper_support_collision\n"
      + "# The names of the links the object to be attached is allowed to touch;\n"
      + "# If this is left empty, it defaults to the links in the used end-effector\n"
      + "string[] attached_object_touch_links\n"
      + "# Optionally notify the pick action that it should approach the object further,\n"
      + "# as much as possible (this minimizing the distance to the object before the grasp)\n"
      + "# along the approach direction; Note: this option changes the grasping poses\n"
      + "# supplied in possible_grasps[] such that they are closer to the object when possible.\n"
      + "bool minimize_object_distance\n"
      + "# Optional constraints to be imposed on every point in the motion plan\n"
      + "Constraints path_constraints\n"
      + "# The name of the motion planner to use. If no name is specified,\n"
      + "# a default motion planner will be used\n"
      + "string planner_id\n"
      + "# an optional list of obstacles that we have semantic information about\n"
      + "# and that can be touched/pushed/moved in the course of grasping;\n"
      + "# CAREFUL: If the object name \'all\' is used, collisions with all objects are disabled during the approach & lift.\n"
      + "string[] allowed_touch_objects\n"
      + "# The maximum amount of time the motion planner is allowed to plan for\n"
      + "float64 allowed_planning_time\n"
      + "# Planning options\n"
      + "PlanningOptions planning_options\n"
      + "";
  java.lang.String getTargetName();
  void setTargetName(java.lang.String value);
  java.lang.String getGroupName();
  void setGroupName(java.lang.String value);
  java.lang.String getEndEffector();
  void setEndEffector(java.lang.String value);
  java.util.List<moveit_msgs.Grasp> getPossibleGrasps();
  void setPossibleGrasps(java.util.List<moveit_msgs.Grasp> value);
  java.lang.String getSupportSurfaceName();
  void setSupportSurfaceName(java.lang.String value);
  boolean getAllowGripperSupportCollision();
  void setAllowGripperSupportCollision(boolean value);
  java.util.List<java.lang.String> getAttachedObjectTouchLinks();
  void setAttachedObjectTouchLinks(java.util.List<java.lang.String> value);
  boolean getMinimizeObjectDistance();
  void setMinimizeObjectDistance(boolean value);
  moveit_msgs.Constraints getPathConstraints();
  void setPathConstraints(moveit_msgs.Constraints value);
  java.lang.String getPlannerId();
  void setPlannerId(java.lang.String value);
  java.util.List<java.lang.String> getAllowedTouchObjects();
  void setAllowedTouchObjects(java.util.List<java.lang.String> value);
  double getAllowedPlanningTime();
  void setAllowedPlanningTime(double value);
  moveit_msgs.PlanningOptions getPlanningOptions();
  void setPlanningOptions(moveit_msgs.PlanningOptions value);
}
