package moveit_msgs;

public interface PickupResult {
  static final java.lang.String _TYPE = "moveit_msgs/PickupResult";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#result definition\n"
      + "# The overall result of the pickup attempt\n"
      + "MoveItErrorCodes error_code\n"
      + "# The full starting state of the robot at the start of the trajectory\n"
      + "RobotState trajectory_start\n"
      + "# The trajectory that moved group produced for execution\n"
      + "RobotTrajectory[] trajectory_stages\n"
      + "string[] trajectory_descriptions\n"
      + "# The performed grasp, if attempt was successful\n"
      + "Grasp grasp\n"
      + "# The amount of time in seconds it took to complete the plan\n"
      + "float64 planning_time\n"
      + "";
  moveit_msgs.MoveItErrorCodes getErrorCode();
  void setErrorCode(moveit_msgs.MoveItErrorCodes value);
  moveit_msgs.RobotState getTrajectoryStart();
  void setTrajectoryStart(moveit_msgs.RobotState value);
  java.util.List<moveit_msgs.RobotTrajectory> getTrajectoryStages();
  void setTrajectoryStages(java.util.List<moveit_msgs.RobotTrajectory> value);
  java.util.List<java.lang.String> getTrajectoryDescriptions();
  void setTrajectoryDescriptions(java.util.List<java.lang.String> value);
  moveit_msgs.Grasp getGrasp();
  void setGrasp(moveit_msgs.Grasp value);
  double getPlanningTime();
  void setPlanningTime(double value);
}
