package moveit_msgs;

public interface PlaceGoal {
  static final java.lang.String _TYPE = "moveit_msgs/PlaceGoal";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#goal definition# An action for placing an object\n"
      + "# which group to be used to plan for grasping\n"
      + "string group_name\n"
      + "# the name of the attached object to place\n"
      + "string attached_object_name\n"
      + "# a list of possible transformations for placing the object\n"
      + "PlaceLocation[] place_locations\n"
      + "# if the user prefers setting the eef pose (same as in pick) rather than \n"
      + "# the location of the object, this flag should be set to true\n"
      + "bool place_eef\n"
      + "# the name that the support surface (e.g. table) has in the collision world\n"
      + "# can be left empty if no name is available\n"
      + "string support_surface_name\n"
      + "# whether collisions between the gripper and the support surface should be acceptable\n"
      + "# during move from pre-place to place and during retreat. Collisions when moving to the\n"
      + "# pre-place location are still not allowed even if this is set to true.\n"
      + "bool allow_gripper_support_collision\n"
      + "# Optional constraints to be imposed on every point in the motion plan\n"
      + "Constraints path_constraints\n"
      + "# The name of the motion planner to use. If no name is specified,\n"
      + "# a default motion planner will be used\n"
      + "string planner_id\n"
      + "# an optional list of obstacles that we have semantic information about\n"
      + "# and that can be touched/pushed/moved in the course of placing;\n"
      + "# CAREFUL: If the object name \'all\' is used, collisions with all objects are disabled during the approach & retreat.\n"
      + "string[] allowed_touch_objects\n"
      + "# The maximum amount of time the motion planner is allowed to plan for\n"
      + "float64 allowed_planning_time\n"
      + "# Planning options\n"
      + "PlanningOptions planning_options\n"
      + "";
  java.lang.String getGroupName();
  void setGroupName(java.lang.String value);
  java.lang.String getAttachedObjectName();
  void setAttachedObjectName(java.lang.String value);
  java.util.List<moveit_msgs.PlaceLocation> getPlaceLocations();
  void setPlaceLocations(java.util.List<moveit_msgs.PlaceLocation> value);
  boolean getPlaceEef();
  void setPlaceEef(boolean value);
  java.lang.String getSupportSurfaceName();
  void setSupportSurfaceName(java.lang.String value);
  boolean getAllowGripperSupportCollision();
  void setAllowGripperSupportCollision(boolean value);
  moveit_msgs.Constraints getPathConstraints();
  void setPathConstraints(moveit_msgs.Constraints value);
  java.lang.String getPlannerId();
  void setPlannerId(java.lang.String value);
  java.util.List<java.lang.String> getAllowedTouchObjects();
  void setAllowedTouchObjects(java.util.List<java.lang.String> value);
  double getAllowedPlanningTime();
  void setAllowedPlanningTime(double value);
  moveit_msgs.PlanningOptions getPlanningOptions();
  void setPlanningOptions(moveit_msgs.PlanningOptions value);
}
