package moveit_msgs;

public interface PlaceAction {
  static final java.lang.String _TYPE = "moveit_msgs/PlaceAction";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "PlaceActionGoal action_goal\n"
      + "PlaceActionResult action_result\n"
      + "PlaceActionFeedback action_feedback\n"
      + "";
  moveit_msgs.PlaceActionGoal getActionGoal();
  void setActionGoal(moveit_msgs.PlaceActionGoal value);
  moveit_msgs.PlaceActionResult getActionResult();
  void setActionResult(moveit_msgs.PlaceActionResult value);
  moveit_msgs.PlaceActionFeedback getActionFeedback();
  void setActionFeedback(moveit_msgs.PlaceActionFeedback value);
}
