package moveit_msgs;

public interface PlaceActionResult {
  static final java.lang.String _TYPE = "moveit_msgs/PlaceActionResult";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "Header header\n"
      + "actionlib_msgs/GoalStatus status\n"
      + "moveit_msgs/PlaceResult result\n"
      + "";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  moveit_msgs.PlaceResult getResult();
  void setResult(moveit_msgs.PlaceResult value);
}
