package moveit_msgs;

public interface PlaceFeedback {
  static final java.lang.String _TYPE = "moveit_msgs/PlaceFeedback";
  static final java.lang.String _DEFINITION = ""
      + "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
      + "#feedback definition\n"
      + "# The internal state that the place action currently is in\n"
      + "string state\n"
      + "";
  java.lang.String getState();
  void setState(java.lang.String value);
}
